---
- name: Update Repositories cache and Install "docker.io" package
  apt:
    name: docker.io
    update_cache: yes

- name: Ensure Docker is enabled and running
   service:
     name: docker
     state: started
     enabled: yes
  
- name: Download and dearmor Kubernetes Signing Key
  shell: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v{{ k8_version }}/deb/Release.key | \
    gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes Software Repositories
  apt_repository:
    repo: "deb https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/ /"
    state: present
    update_cache: yes
 
- name: Install Kubernetes Tools
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
   # state: present

- name: Hold Kubernetes Tools
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl

- name: Check Kubernetes Tools Versions
  command: "{{ item }} --version"
  loop: "{{ k8s_tools }}"
  changed_when: false
  failed_when: false 
