- name: Update Repositories Cache and Install "docker.io"
  apt:
    name: docker.io
    update_cache: yes

- name: Ensure Docker is enabled and running
  service:
    name: docker
    state: started
    enabled: yes
- name: Install Required Packages for Apt Repository
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: yes

- name: Download Kubernetes Signing Key
  get_url:
    url: https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/Release.key
    dest: /tmp/kubernetes-release.key
    mode: '0644'

- name: Dearmor and Install Kubernetes Signing Key
  shell: |
    cat /tmp/kubernetes-release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes Apt Repository
  apt_repository:
    repo: "deb https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/ /"
    state: present
    update_cache: yes

- name: Install Kubernetes Tools
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
  #state: present

- name: Hold the Kubernetes Tools
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl

- name: Verify Kubernetes Tools Versions
  command: "{{ item }} --version"
  loop: "{{ k8s_tools }}"
  register: k8s_versions
  changed_when: false
  failed_when: false

- name: Display Kubernetes Tools Versions Verified
  debug:
    msg: "Kubernetes Tools Versions verified"
