- name: Update Apt Packages
  apt:
    update_cache: yes
  register: apt_update_result

- name: Install Docker Package 
  apt:
    name: docker.io
    state: present
  #when: ansible_os_family == "Debian"

- name: Start Docker Service
  service:
    name: docker
    enabled: yes
    state: started

- name: Verify Docker Is Running
  service:
    name: docker
    state: started
  register: docker_stat

- name: Add Kubernetes Signing Key
  apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/Release.key
    state: present

- name: Add Kubernetes Software Repositories
  apt_repository:
    repo: "deb https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/ /"
    state: present
    filename: kubernetes

- name: Update Apt Packages
  apt:
    update_cache: yes
  register: apt_update_result #or when: ansible_os_family == "Debian"

- name: Install Kubernetes Tools
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present

    #- name: Install Kubernetes Tools (kubeadm, kubelet, kubectl)
    #  pkg:
    #    loop:
    #      - kubeadm
    #      - kubelet
    #      - kubectl
    #        #state: present
  
- name: Hold Kubernetes Tools
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl

- name: Check Kubernetes tools versions
  command: "{{ item }} --version"
  loop: "{{ k8s_tools }}"
  register: k8s_versions
  changed_when: false
  failed_when: false

- name: Disable Swap
  shell: |
    swapoff -a
    sed -i '/swap/d' /etc/fstab  # sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

- name: Write Content To containerd.conf File
  copy:
    content: |
      overlay
      br_netfilter
    dest: /etc/modules-load.d/containerd.conf
    backup: yes

- name: Add The Required Containerd Modules
  modprobe:
    name: overlay
    state: present

- name: Write Content To kubernetes.conf File
  copy:
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
    dest: /etc/sysctl.d/kubernetes.conf
    backup: yes
            
