---
- name: Disable Swap
  shell: |
    swapoff -a
    sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab #sed -i '/swap/d' /etc/fstab

#- name: Disable All Swap Spaces Using swapoff command
#  command: swapoff -a
#  register: swapoff_result
#  changed_when: swapoff_result.rc == 0

#- name: Use sed command To Adjust File
#  command: sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
#  register: sed_result
#  changed_when: sed_result.rc == 0
#  when: false

- name: Copy the Modules Content To containerd.conf File
  copy:
    content: |
      overlay
      br_netfilter
    dest: /etc/modules-load.d/containerd.conf
    backup: yes

- name: Add The Required containerd Modules
  modprobe:
    name: overlay
    state: present

- name: Copy Content To kubernetes.conf File
  copy:
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
    dest: /etc/sysctl.d/kubernetes.conf
    backup: yes

- name: Reload The containerd modules
  service:
    name: containerd
    enabled: yes
    state: restarted

- name: Set Hostname to "master-node" for Ubuntu
  hostname:
    name: master-node

- name: Add "master-node" Hostname to hosts file
  lineinfile:
    path: /etc/hosts
    line: "127.1.1.1 master-node"
    insertafter: "^ubuntu.myguest.virtualbox.org    ubuntu.*"
    backup: yes

- name: Copy Content to the kubelet file
  copy:
    content: |
      KUBELET_EXTRA_ARGS="--cgroup-driver=cgroupfs"
    dest: /etc/default/kubelet
    backup: yes

- name: Reload daemon configuration and Restart kubelet
  service:
    name: kubelet
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Copy Content to the kubelet file
  copy:
    content: |
      {
            "exec-opts": ["native.cgroupdriver=systemd"],
            "log-driver": "json-file",
            "log-opts": {
            "max-size": "100m"
         },
             "storage-driver": "overlay2"
             }
    dest: /etc/docker/daemon.json
    backup: yes

- name: Reload systemd daemon and Restart Docker
  service:
    name: docker
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Add a Service Line to kubeadm.conf file
  lineinfile:
    path: /usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf
    insertafter: '^Environment="KUBELET_CONFIG_ARGS=--config=/var/lib/kubelet/config.yaml'
    line: 'Environment="KUBELET_EXTRA_ARGS=--fail-swap-on=false"'
    backup: yes

- name: Reload systemd daemon and Restart kubelet
  service:
    name: kubelet
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Initialize Kubernetes cluster with kubeadm
  command:
    cmd: kubeadm init --control-plane-endpoint=master-node --upload-certs
