---
- name: Disable Swap
  shell: |
    swapoff -a
    sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab #sed -i '/swap/d' /etc/fstab

- name: Copy the Modules Content To containerd.conf File
  copy:
    content: |
      overlay
      br_netfilter
    dest: /etc/modules-load.d/containerd.conf
    backup: yes

- name: Add The Required containerd Modules
  modprobe:
    name: overlay
    state: present

- name: Copy Content To kubernetes.conf File
  copy:
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
    dest: /etc/sysctl.d/kubernetes.conf
    backup: yes

- name: Reload The containerd modules
  service:
    name: containerd
    enabled: yes
    state: restarted

- name: Set Hostname to "master-node" for Ubuntu
  hostname:
    name: master-node

- name: Add "master-node" Hostname to hosts file
  lineinfile:
    path: /etc/hosts
    line: "127.1.1.1 master-node" 
    insertafter: "^ubuntu.myguest.virtualbox.org    ubuntu.*"
    backup: yes

- name: Copy Content to the kubelet file
  copy:
    content: |
      KUBELET_EXTRA_ARGS="--cgroup-driver=cgroupfs"
    dest: /etc/default/kubelet
    backup: yes

- name: Reload daemon configuration and Restart kubelet
  service:
    name: kubelet
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Copy Content to the kubelet file
  copy:
    content: |
      {
            "exec-opts": ["native.cgroupdriver=systemd"],
            "log-driver": "json-file",
            "log-opts": {
            "max-size": "100m"
         },
             "storage-driver": "overlay2"
             }
    dest: /etc/docker/daemon.json
    backup: yes

- name: Reload systemd daemon and Restart Docker
  service:
    name: docker
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Add a Service Line to kubeadm.conf file
  lineinfile:
    path: /usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf
    insertafter: '^Environment="KUBELET_CONFIG_ARGS=--config=/var/lib/kubelet/config.yaml'
    line: 'Environment="KUBELET_EXTRA_ARGS=--fail-swap-on=false"'
    backup: yes

- name: Reload systemd daemon and Restart kubelet
  service:
    name: kubelet
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Initialize Kubernetes cluster with kubeadm
  command:
    cmd: kubeadm init --control-plane-endpoint=master-node --upload-certs

 - name: Create a Directory for the Kubernetes Cluster
   command:
     cmd: mkdir -p $HOME/.kube

- name: Copy Configuration File to the Directory
  copy:
    content: |
      cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    dest: $HOME/.kube
    backup: yes

- name: Change The Ownership of the Directory
  command:
    cmd: chown $(id -u):$(id -g) $HOME/.kube/config

- name: Use kubectl to Install Flannel
  command:
    cmd: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml

- name: Use kubectl to Untaint the Node
  command:
    cmd: kubectl taint nodes --all node-role.kubernetes.io/control-plane-

- name: Check the status of the nodes
  command:
    cmd: kubectl get nodes

- name: 
  debug:
    msg: "Display info. about the nodes in the cluster"
    
